# Generated by Django 4.0 on 2022-08-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Uidx',
            new_name='id',
        ),
    ]
